f_train = "./data/NYTaxi/flow_train.npz"
f_test = "./data/NYTaxi/flow_test.npz"
t_train = "./data/NYTaxi/trans_train.npz"
t_test = "./data/NYTaxi/trans_test.npz"
ex_train = "./data/NYTaxi/ex_knlg_train.npz"
ex_test = "./data/NYTaxi/ex_knlg_test.npz"
f_train_max = 1518.0
f_test_max = 1427.0
t_train_max = 186.0
t_test_max = 186.0
n_sec_int = 1800
n_int_day = 48
total_day = 60
n_int = total_day * 24 * 60 * 60 / n_sec_int
loss_threshold = 10
len_x = 12
len_y = 16