f_train = "./data/NYBike/flow_train.npz"
f_test = "./data/NYBike/flow_test.npz"
t_train = "./data/NYBike/trans_train.npz"
t_test = "./data/NYBike/trans_test.npz"
ex_train = "./data/NYBike/ex_knlg_train.npz"
ex_test = "./data/NYBike/ex_knlg_test.npz"
f_train_max = 295.0
f_test_max = 295.0
t_train_max = 39.0
t_test_max = 39.0
n_sec_int = 1800
n_int_day = 48
n_day = 60
n_int = n_day * 24 * 60 * 60 / n_sec_int
loss_threshold = 10
len_x = 8
len_y = 14