data_train = "./data/NYTaxi/taxi_train.npz"
data_val = "./data/NYTaxi/taxi_val.npz"
data_test = "./data/NYTaxi/taxi_test.npz"
data_max = 1518.0
t_max = 174.0
n_sec_int = 1800
n_int_day = 48
test_threshold = [10, 10]
len_r = 16
len_c = 12
data_name = ['inflow', 'outflow']
data_type = 2